SCRIPT=$1
N=$2
BASENAME=$(basename "$SCRIPT")
LOGSDIR="./logs"
mkdir -p $LOGSDIR
OUTFILE=$LOGSDIR"/"$BASENAME".out"
ERRORFILE=$LOGSDIR"/"$BASENAME".error"
touch $OUTFILE
touch $ERRORFILE
INTERPRETER=python3
for i in $(seq 1 $N)
do $INTERPRETER $SCRIPT 1> $OUTFILE 2> $ERRORFILE &
sleep 1
done
